### ISSUE TITLE
人脸检测与包围盒回归之间的关系是什么？人脸检测与配准之间的关系又是什么？求解答

### ISSUE THREAD

**Issue by xml94** [kpzhang93/MTCNN_face_detection_alignment#36]
文章摘要和引言中多次提到人脸特征点定位于包围盒回归之间的关系，以及人脸检测与配准之间的关系。
我不是十分明白这两者之间的关系是什么，或者说文章中这个关系是什么。
另外，我不理解文章中又是怎么利用这个关系的。
谢谢

**Comment by haneSier** [comment]
最好是看源代码中boundingbox regression和boxes alignment 那部分，可以参考这个代码https://github.com/Sierkinhane/mtcnn-pytorch

**Comment by quanok110** [comment]
calibrate box那里也是一直看不懂
