### ISSUE TITLE
Missing CaffeBinding.h

### ISSUE THREAD

**Issue by atoum84** [kpzhang93/MTCNN_face_detection_alignment#6]
I find it in your caffe library

**Comment by baifanysu** [comment]
I cannot find the file? thanks for point to me

**Comment by atoum84** [comment]
Sorry I couldn't find anymore the file (it take me a very long time to find it last weekend).

I put in a zip the two files missing

[caffebinding.tar.gz](https://github.com/kpzhang93/MTCNN_face_detection_alignment/files/587156/caffebinding.tar.gz)
