### ISSUE TITLE
Model - param has no field named "transpose" and "predict_box_param" 

### ISSUE THREAD

**Issue by atoum84** [kpzhang93/MTCNN_face_detection_alignment#7]
Hello,

When I execute MTCNN on linux, some fields are not recognizing by the caffe library and I have the followings errors : 
### 
_[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 12:12: Message type "caffe.MemoryDataParameter" has no field named "transpose".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1112 10:53:38.052264  3463 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: det1-memory.prototxt
*** Check failure stack trace: ***_

This error is related to the proto "memory_data_param" which has no "transpose" field

When I remove this field of the model "det1-memory.prototxt", a new error appear :

  _[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 196:21: Message type "caffe.LayerParameter" has no field named "predict_box_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1112 10:55:39.076514  3523 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: det1-memory.prototxt
*** Check failure stack trace: ***_

This time, caffe don't know the layer of type "PredictBox".

If I remove this layer of the file, the model success to load but at the runtime, I have the following error :

_F1112 10:37:54.543467  3165 data_transformer.cpp:290] Check failed: img_height == height (360 vs. 256)_   

I think to resolve the problem I need to modify the proto layers of caffe but I don't know exactly how.

I use :
 + source code : MTCNN_face_detection_alignment/code/codes/vs/CascadeFaceDetection/
 + model : MTCNN_face_detection_alignment/code/codes/MTCNNv2/model/
                  + det1-memory.prototxt and det1.caffemodel
                  + det1-memory-stitch.prototxt  and det1.caffemodel
                  + det2-memory.prototxt and det2.caffemodel
                  + det3-memory.prototxt and det3.caffemodel
                  + det4-memory.prototxt and det4.caffemodel

**Comment by atoum84** [comment]
Find the missing layers elements in https://github.com/happynear/caffe-windows/tree/ms

**Comment by raullalves** [comment]
I have the same problem. How did you manage to solve it ?
