### ISSUE TITLE
Face Alignment

### ISSUE THREAD

**Issue by affromero** [kpzhang93/MTCNN_face_detection_alignment#8]
After running demo.m on MTCNNv1 or v2, how can I align that face with respect to the eye points? Is there code to do so?

**Comment by kli-nlpr** [comment]
Maybe you can refer to this
https://github.com/ydwen/caffe-face/blob/caffe-face/face_example/extractDeepFeature.m

**Comment by yekeping** [comment]
Do you solve your question?
